version: '3.8'

services:
  web:
    container_name: kiii-web
    image: kiii-web:latest
    build: .
    restart: unless-stopped
    ports:
      - "8080:8080"

  db:
    image: postgres:latest
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: kiii
    restart: unless-stopped
